### ISSUE TITLE
Latest release of Nop.Plugin.Api.Tests does not compile

### ISSUE THREAD

**Issue by alaingmail** [SevenSpikes/nopCommerce#82]
Hi,

The latest release of this web api branch does not compile for Nop.Plugin.Api.Tests. I downloaded it yesterday. I did not clone it. That should not make a difference.

Here are the errors I'm seeing:

- The type or namespace name 'ISerializableObject' could not be found (are you missing a using directive or an assembly reference?) Nop.Plugin.Api.Tests D:_depot\Test\nopCommerce-Web-Api-3.70\src\Tests\Nop.Plugin.Api.Tests\SerializersTests\DummyObjects\SerializableDummyObjectWithSimpleTypes.cs. This was corrected by adding "using Nop.Plugin.Api.DTOs;" to SerializableDummyObjectWithComplexTypes.cs.

- The same error occurs for SerializableDummyObjectWithSimpleTypes.cs with the same fix.
 
- The type or namespace name 'CreateMap' does not exist in the namespace 'Nop.Plugin.Api.Maps' (are you missing an assembly reference?) Nop.Plugin.Api.Tests D:_depot\Test\nopCommerce-Web-Api-3.70\src\Tests\Nop.Plugin.Api.Tests\ControllersTests\ShoppingCartItems\ShoppingCartItemsControllerTests_GetShoppingCartItemsByCustomerId.cs. This occurs for "Maps.CreateMap();". I'm assuming this is an AutoMapper map definition, but I'm not faimiliar with this format. Changing to **AutoMapper.Mapper.CreateMap();** works.

Cheers,
Alain

**Comment by poyker** [comment]
Thank you for reporting this!

Everything should compile now but some of the tests need to be updated as they are failing now.
