### ISSUE TITLE
How do i get the username and password for the nop.plugin.api

### ISSUE THREAD

**Issue by karcshub** [SevenSpikes/nopCommerce#87]
I have successfully installed nop.plugin.api but when i try to access the service it asks for the username and password,How can i get them?
Thanks!

**Comment by poyker** [comment]
You don't need username and password. You need to pass the Access Token that you need to obtain first.
Please refer to this Sample Application that explains how the authentication works and how to obtain and later use the Access Token.
https://github.com/SevenSpikes/nopCommerce-Api-SampleApplication

Please let me know if have any problems!

**Comment by karcshub** [comment]
Thanks!,i will try it out and see if it will solve my issue because
whenever i was trying to visit the service at localhost using a link like
"localhost:15660/api/customers" a small dialog was popping asking for the
user name and password

**Comment by poyker** [comment]
If you want to test the service directly from the browser you can do so from the Swagger documentation page.
You need to enable this setting from the API plugin settings: Allow Requests From Swagger
Then you can visit this page:
localhost:15660/swagger/ui/index

From there you can make GET requests and test the API.
Please let me know if you mange to run it or if you have any problems.

p.s: We will upgrade the plugin for nopCommerce 3.80 and move it in a different repository and will add a link to it once it is ready.

**Comment by karcshub** [comment]
hey,how are doing today?,
I managed to run it but after going through some bit of hustle but it was
worth it

**Comment by karcshub** [comment]
Am on the page for registering new clients and am wondering what i should
put in the field for call back url
Thanks!
