### ISSUE TITLE
Has anyone used the nop.plugin.api in an android app

### ISSUE THREAD

**Issue by karcshub** [SevenSpikes/nopCommerce#88]
Am trying out the nop.plugin.api for my android app and wondering if any one has come up with a fully working app that is already running in google play store,if so please provide a link

**Comment by poyker** [comment]
@karcshub 

Since the plugins is not officially released I don't think someone has a working app with it.
Please note that we moved the plugin to a new repo and now it officially supports nopCommerce 3.80.
https://github.com/SevenSpikes/api-plugin-for-nopcommerce

Please add your comments in the new repo!

**Comment by karcshub** [comment]
Okay thanks,am working on a nopcommerce project and my client wants a
mobile app for it.Would you advice me to go ahead and use it to expose data
to the mobile app.Thanks

**Comment by poyker** [comment]
Sure. Contact us via email sales at nop-templates.com and we will advise.
Also please write your comments in the new repo as this one will not be monitored anymore.

**Comment by suddenelfilio** [comment]
I attended the devdays and left some comments/feedback about the plugin on the official nopcommerce repo.
See more info nopsolutions/nopcommerce#20

**Comment by poyker** [comment]
@suddenelfilio 

Thank you for your feedback! It is much appreciated!

Since you wrote in the nopCommerce repo I will reply to you there but please in the future use the official API plugin for nopCommerce repo - https://github.com/SevenSpikes/api-plugin-for-nopcommerce
